# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Elena Renn
tab_title: Your Comic! #This text shows up on the browser tab
email:
description: Here's the description of your comic!
url           : "https://greenbootlaces.github.io" # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank

# Comic Social Media
twitter_username: https://twitter.com/greenbootlaces
tumblr_username: http://peahat.tumblr.com
patreon_username: peahat

# Author Social Media
author_twitter_username: https://twitter.com/greenbootlaces
author_tumblr_username: https://green-bootlaces.tumblr.com/
author_instagram_username: https://instagram.com/greenbootlaces
author_patreon_username:



# Build settings
markdown: kramdown

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

defaults:
  - scope:
      path: "comics"
    values:
      permalink: "/:categories/:title"
